In [1]:
from sklearn.preprocessing import MinMaxScaler

In [2]:
import pandas as pd

In [4]:
sp500_training_complete = pd.read_csv("GSPC.csv")

In [5]:
sp500_training_processed = sp500_training_complete.iloc[:, 4:5].values  

In [6]:
scaler = MinMaxScaler(feature_range = (0, 1))

sp500_training_scaled = scaler.fit_transform(sp500_training_processed)

In [79]:
np.array(sp500_training_scaled)[:50]

array([[0.        ],
       [0.01176152],
       [0.01883373],
       [0.02213084],
       [0.0234192 ],
       [0.02051687],
       [0.02231779],
       [0.0451621 ],
       [0.05175625],
       [0.04911722],
       [0.057637  ],
       [0.04661669],
       [0.07125491],
       [0.04798123],
       [0.06667637],
       [0.08896652],
       [0.10232112],
       [0.12571258],
       [0.11333458],
       [0.10027084],
       [0.1090262 ],
       [0.09749323],
       [0.07373472],
       [0.08332818],
       [0.10106743],
       [0.13452332],
       [0.1427661 ],
       [0.14246137],
       [0.15494329],
       [0.14230207],
       [0.1176499 ],
       [0.1229627 ],
       [0.10181548],
       [0.1171928 ],
       [0.13992617],
       [0.15510952],
       [0.14253062],
       [0.14166478],
       [0.15046165],
       [0.17906893],
       [0.18964601],
       [0.1909413 ],
       [0.19715453],
       [0.21625147],
       [0.22080921],
       [0.22153654],
       [0.22103776],
       [0.200

In [33]:
def method(x,a,b):
    return (((b - a)*(x - min(x))) / (max(x) - min(x))) + a

In [34]:
my = method(sp500_training_processed,0,1)
np.array(my)

array([[0.        ],
       [0.01176152],
       [0.01883373],
       [0.02213084],
       [0.0234192 ],
       [0.02051687],
       [0.02231779],
       [0.0451621 ],
       [0.05175625],
       [0.04911722],
       [0.057637  ],
       [0.04661669],
       [0.07125491],
       [0.04798123],
       [0.06667637],
       [0.08896652],
       [0.10232112],
       [0.12571258],
       [0.11333458],
       [0.10027084],
       [0.1090262 ],
       [0.09749323],
       [0.07373472],
       [0.08332818],
       [0.10106743],
       [0.13452332],
       [0.1427661 ],
       [0.14246137],
       [0.15494329],
       [0.14230207],
       [0.1176499 ],
       [0.1229627 ],
       [0.10181548],
       [0.1171928 ],
       [0.13992617],
       [0.15510952],
       [0.14253062],
       [0.14166478],
       [0.15046165],
       [0.17906893],
       [0.18964601],
       [0.1909413 ],
       [0.19715453],
       [0.21625147],
       [0.22080921],
       [0.22153654],
       [0.22103776],
       [0.200

In [23]:
my == sp500_training_scaled

array([[ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [19]:
np.array_equal(my, sp500_training_scaled)

False

In [7]:
import numpy as np

In [35]:
np.append(np.append(my,sp500_training_scaled, axis=1),my-sp500_training_scaled, axis=1)

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 1.17615151e-02,  1.17615151e-02, -5.37764278e-17],
       [ 1.88337282e-02,  1.88337282e-02, -2.42861287e-17],
       [ 2.21308420e-02,  2.21308420e-02,  2.77555756e-17],
       [ 2.34191969e-02,  2.34191969e-02, -9.36750677e-17],
       [ 2.05168680e-02,  2.05168680e-02,  3.46944695e-18],
       [ 2.23177914e-02,  2.23177914e-02,  2.77555756e-17],
       [ 4.51621031e-02,  4.51621031e-02, -1.17961196e-16],
       [ 5.17562455e-02,  5.17562455e-02, -1.59594560e-16],
       [ 4.91172190e-02,  4.91172190e-02, -4.85722573e-17],
       [ 5.76370026e-02,  5.76370026e-02, -4.85722573e-17],
       [ 4.66166917e-02,  4.66166917e-02, -9.02056208e-17],
       [ 7.12549094e-02,  7.12549094e-02, -9.71445147e-17],
       [ 4.79812306e-02,  4.79812306e-02, -1.52655666e-16],
       [ 6.66763736e-02,  6.66763736e-02, -1.24900090e-16],
       [ 8.89665158e-02,  8.89665158e-02, -2.77555756e-17],
       [ 1.02321119e-01,  1.02321119e-01

In [27]:
my.shape

(322, 1)

In [44]:
sp500_training_scaled[50-50:50,0].shape

(50,)

In [8]:
features_set = []  
labels = []  
for i in range(50, 322):
    features_set.append(sp500_training_scaled[i-50:i, 0])
    #print(features_set)
    labels.append(sp500_training_scaled[i, 0])
    #break

In [9]:
features_set, labels = np.array(features_set), np.array(labels)

In [38]:
features_set

array([[[0.        ],
        [0.01176152],
        [0.01883373],
        ...,
        [0.20041697],
        [0.23020176],
        [0.24618863]],

       [[0.01176152],
        [0.01883373],
        [0.02213084],
        ...,
        [0.23020176],
        [0.24618863],
        [0.23924113]],

       [[0.01883373],
        [0.02213084],
        [0.0234192 ],
        ...,
        [0.24618863],
        [0.23924113],
        [0.2468605 ]],

       ...,

       [[0.8769404 ],
        [0.76351576],
        [0.79995718],
        ...,
        [0.8463728 ],
        [0.89328053],
        [0.90510428]],

       [[0.76351576],
        [0.79995718],
        [0.77474391],
        ...,
        [0.89328053],
        [0.90510428],
        [0.91273751]],

       [[0.79995718],
        [0.77474391],
        [0.81064502],
        ...,
        [0.90510428],
        [0.91273751],
        [0.87074797]]])

In [9]:
features_set.shape

(272, 50)

In [39]:
labels

array([0.23924113, 0.2468605 , 0.24431837, 0.2107863 , 0.20545269,
       0.21544795, 0.24426992, 0.24262136, 0.25869126, 0.27156805,
       0.24600159, 0.26358848, 0.25742371, 0.26259793, 0.22838004,
       0.26243169, 0.26142736, 0.27371531, 0.27187278, 0.27144333,
       0.28714618, 0.30310523, 0.32102458, 0.311826  , 0.33032717,
       0.32900415, 0.34596068, 0.33358268, 0.34095963, 0.34104275,
       0.3041997 , 0.30866045, 0.32491747, 0.34801104, 0.35838029,
       0.36138645, 0.34603002, 0.36324977, 0.3441667 , 0.33381132,
       0.29102511, 0.27760811, 0.33151161, 0.36854871, 0.37815603,
       0.38362806, 0.40003051, 0.40284279, 0.40825258, 0.35765988,
       0.40498303, 0.41753428, 0.39635933, 0.38708456, 0.36949767,
       0.39194017, 0.35257571, 0.39446835, 0.423228  , 0.43244747,
       0.42842996, 0.40540563, 0.39303448, 0.43092364, 0.3983127 ,
       0.40242712, 0.42673988, 0.41227686, 0.43756623, 0.4310552 ,
       0.43646499, 0.44105731, 0.44336395, 0.4304317 , 0.42034

In [10]:
features_set = np.reshape(features_set, (features_set.shape[0], features_set.shape[1], 1))  

In [12]:
features_set.shape

(272, 50, 1)

In [130]:
x = features_set[0,:,:]
y = np.array(sp500_training_scaled[:50])

In [133]:
x

array([[0.        ],
       [0.01176152],
       [0.01883373],
       [0.02213084],
       [0.0234192 ],
       [0.02051687],
       [0.02231779],
       [0.0451621 ],
       [0.05175625],
       [0.04911722],
       [0.057637  ],
       [0.04661669],
       [0.07125491],
       [0.04798123],
       [0.06667637],
       [0.08896652],
       [0.10232112],
       [0.12571258],
       [0.11333458],
       [0.10027084],
       [0.1090262 ],
       [0.09749323],
       [0.07373472],
       [0.08332818],
       [0.10106743],
       [0.13452332],
       [0.1427661 ],
       [0.14246137],
       [0.15494329],
       [0.14230207],
       [0.1176499 ],
       [0.1229627 ],
       [0.10181548],
       [0.1171928 ],
       [0.13992617],
       [0.15510952],
       [0.14253062],
       [0.14166478],
       [0.15046165],
       [0.17906893],
       [0.18964601],
       [0.1909413 ],
       [0.19715453],
       [0.21625147],
       [0.22080921],
       [0.22153654],
       [0.22103776],
       [0.200

In [134]:
np.append(x,y,axis=1)

array([[0.        , 0.        ],
       [0.01176152, 0.01176152],
       [0.01883373, 0.01883373],
       [0.02213084, 0.02213084],
       [0.0234192 , 0.0234192 ],
       [0.02051687, 0.02051687],
       [0.02231779, 0.02231779],
       [0.0451621 , 0.0451621 ],
       [0.05175625, 0.05175625],
       [0.04911722, 0.04911722],
       [0.057637  , 0.057637  ],
       [0.04661669, 0.04661669],
       [0.07125491, 0.07125491],
       [0.04798123, 0.04798123],
       [0.06667637, 0.06667637],
       [0.08896652, 0.08896652],
       [0.10232112, 0.10232112],
       [0.12571258, 0.12571258],
       [0.11333458, 0.11333458],
       [0.10027084, 0.10027084],
       [0.1090262 , 0.1090262 ],
       [0.09749323, 0.09749323],
       [0.07373472, 0.07373472],
       [0.08332818, 0.08332818],
       [0.10106743, 0.10106743],
       [0.13452332, 0.13452332],
       [0.1427661 , 0.1427661 ],
       [0.14246137, 0.14246137],
       [0.15494329, 0.15494329],
       [0.14230207, 0.14230207],
       [0.

In [157]:
np.reshape(np.array(sp500_training_scaled), (272,-1))

ValueError: cannot reshape array of size 322 into shape (272,newaxis)

In [154]:
sp500_training_scaled.shape

(322, 1)

In [146]:
a = np.arange(10)
print (a)
print (np.reshape(a,(5,2)))
print (np.reshape(a,(5,-1)))


[0 1 2 3 4 5 6 7 8 9]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [11]:
import keras
from keras.models import Sequential  
from keras.layers import Dense  
from keras.layers import LSTM  
from keras.layers import Dropout  

Using TensorFlow backend.


In [12]:
model = Sequential()  
model.add(LSTM(units=50, return_sequences=True, input_shape=(features_set.shape[1], 1),unroll=False))
model.add(Dropout(0.2))
model.add(LSTM(units=50, return_sequences=True))  
model.add(Dropout(0.2))

model.add(LSTM(units=50, return_sequences=True))  
model.add(Dropout(0.2))

model.add(LSTM(units=50))  
model.add(Dropout(0.2))
model.add(Dense(units = 1))

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


In [13]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_1 (LSTM)                (None, 50, 50)            10400     
_________________________________________________________________
dropout_1 (Dropout)          (None, 50, 50)            0         
_________________________________________________________________
lstm_2 (LSTM)                (None, 50, 50)            20200     
_________________________________________________________________
dropout_2 (Dropout)          (None, 50, 50)            0         
_________________________________________________________________
lstm_3 (LSTM)                (None, 50, 50)            20200     
_________________________________________________________________
dropout_3 (Dropout)          (None, 50, 50)            0         
_________________________________________________________________
lstm_4 (LSTM)                (None, 50)                20200     
__________

In [14]:
model.add(Dense(units = 1))  
model.compile(optimizer = 'adam', loss = 'mean_squared_error')

In [15]:
print (features_set.shape)
print (labels.shape)


(272, 50, 1)
(272,)


In [104]:
history = model.fit(features_set, labels, epochs = 100, batch_size = 32)

Epoch 1/100
272/272 [==============================] - 1s 4ms/step - loss: 0.0045
Epoch 2/100
272/272 [==============================] - 1s 5ms/step - loss: 0.0048
Epoch 3/100
272/272 [==============================] - 1s 4ms/step - loss: 0.0048
Epoch 4/100
272/272 [==============================] - 1s 4ms/step - loss: 0.0042
Epoch 5/100
272/272 [==============================] - 1s 4ms/step - loss: 0.0042
Epoch 6/100
272/272 [==============================] - 1s 4ms/step - loss: 0.0039
Epoch 7/100
272/272 [==============================] - 1s 4ms/step - loss: 0.0044
Epoch 8/100
272/272 [==============================] - 1s 4ms/step - loss: 0.0039
Epoch 9/100
272/272 [==============================] - 1s 4ms/step - loss: 0.0039
Epoch 10/100
272/272 [==============================] - 1s 5ms/step - loss: 0.0044
Epoch 11/100
272/272 [==============================] - 1s 5ms/step - loss: 0.0048
Epoch 12/100
272/272 [==============================] - 1s 4ms/step - loss: 0.0035
Epoch 13/100


272/272 [==============================] - 1s 5ms/step - loss: 0.0023
Epoch 100/100
272/272 [==============================] - 1s 5ms/step - loss: 0.0026


In [105]:
predictions = model.predict(test_features)

In [29]:
from math import sqrt
from sklearn.metrics import mean_squared_error

In [106]:
predictions = scaler.inverse_transform(predictions)

In [107]:
sqrt(mean_squared_error(sp500_training_processed[51:322], predictions[51:322]))

60.413192755959635

In [55]:
test_features

array([[[0.77474391],
        [0.81064502],
        [0.82023146],
        ...,
        [0.91273751],
        [0.87074797],
        [0.9257528 ]],

       [[0.81064502],
        [0.82023146],
        [0.82007216],
        ...,
        [0.87074797],
        [0.9257528 ],
        [0.        ]],

       [[0.82023146],
        [0.82007216],
        [0.81557674],
        ...,
        [0.9257528 ],
        [0.        ],
        [0.01176152]],

       ...,

       [[0.8769404 ],
        [0.76351576],
        [0.79995718],
        ...,
        [0.8463728 ],
        [0.89328053],
        [0.90510428]],

       [[0.76351576],
        [0.79995718],
        [0.77474391],
        ...,
        [0.89328053],
        [0.90510428],
        [0.91273751]],

       [[0.79995718],
        [0.77474391],
        [0.81064502],
        ...,
        [0.90510428],
        [0.91273751],
        [0.87074797]]])

In [93]:
sp500_testing_complete['Close'].max() - sp500_training_complete['Close'].min()

1443.689942

In [99]:
def myrescale(x):
    maxval = sp500_training_complete['Close'].max()
    minval = sp500_training_complete['Close'].min() # same for this, min max should be of the OG dataset.
    #print (maxval-minval)
    #print (x*(maxval-minval) + minval)
    return (np.array(x*(maxval-minval) + minval))

In [100]:
my_rescale = myrescale(predictions)

In [101]:
print(my_rescale)

[[2778.822 ]
 [2767.4155]
 [2717.2847]
 [2636.748 ]
 [2537.378 ]
 [2429.385 ]
 [2320.421 ]
 [2215.7263]
 [2118.8032]
 [2031.7861]
 [1955.6693]
 [1890.6965]
 [1836.3549]
 [1791.9374]
 [1756.1827]
 [1727.8541]
 [1706.0107]
 [1689.8927]
 [1678.9901]
 [1672.507 ]
 [1669.2623]
 [1668.1829]
 [1668.2122]
 [1668.1952]
 [1667.4208]
 [1665.8672]
 [1664.2571]
 [1663.4252]
 [1663.9061]
 [1666.0035]
 [1669.5393]
 [1673.6876]
 [1677.7097]
 [1680.8032]
 [1682.6804]
 [1683.703 ]
 [1684.619 ]
 [1685.8318]
 [1687.4755]
 [1689.6177]
 [1692.6644]
 [1697.0376]
 [1702.8859]
 [1710.1361]
 [1718.7703]
 [1728.6562]
 [1739.4613]
 [1750.6975]
 [1761.4915]
 [1771.5691]
 [1781.1377]
 [1790.291 ]
 [1799.123 ]
 [1807.5879]
 [1814.988 ]
 [1820.6238]
 [1824.3169]
 [1826.7156]
 [1828.5406]
 [1830.5938]
 [1833.604 ]
 [1837.4768]
 [1842.1041]
 [1847.1825]
 [1852.4513]
 [1857.08  ]
 [1860.9764]
 [1864.2847]
 [1867.3959]
 [1870.585 ]
 [1873.9508]
 [1877.7325]
 [1882.3256]
 [1888.2246]
 [1895.4172]
 [1903.8927]
 [1913.3882]

In [103]:
predictions

array([[2778.822 ],
       [2767.4158],
       [2717.2844],
       [2636.748 ],
       [2537.3782],
       [2429.385 ],
       [2320.421 ],
       [2215.7263],
       [2118.8032],
       [2031.7861],
       [1955.6693],
       [1890.6967],
       [1836.355 ],
       [1791.9374],
       [1756.1827],
       [1727.8542],
       [1706.0107],
       [1689.8927],
       [1678.9902],
       [1672.507 ],
       [1669.2623],
       [1668.183 ],
       [1668.2122],
       [1668.1952],
       [1667.4209],
       [1665.8672],
       [1664.2572],
       [1663.4252],
       [1663.906 ],
       [1666.0037],
       [1669.5393],
       [1673.6876],
       [1677.7098],
       [1680.8031],
       [1682.6804],
       [1683.703 ],
       [1684.619 ],
       [1685.8318],
       [1687.4755],
       [1689.6177],
       [1692.6643],
       [1697.0376],
       [1702.8857],
       [1710.1361],
       [1718.7703],
       [1728.6562],
       [1739.4613],
       [1750.6974],
       [1761.4915],
       [1771.5692],


In [18]:
sp500_testing_complete = pd.read_csv("GSPC.csv")
sp500_testing_processed = sp500_testing_complete.iloc[:, 4:5].values 
sp500_testing_processed.size

322

In [41]:
sp500_total = pd.concat((sp500_training_complete['Close'], sp500_testing_complete['Close']), axis=0)

In [43]:
test_inputs = sp500_total[len(sp500_total) - len(sp500_testing_complete) - 50:].values

In [45]:
len(test_inputs)

372

In [31]:
len(sp500_total) - len(sp500_testing_complete) - 50

272

In [24]:
644 - (len(sp500_total) - len(sp500_testing_complete) - 50)

372

In [46]:
test_inputs = test_inputs.reshape(-1,1)  
test_inputs = scaler.transform(test_inputs)

In [47]:
test_inputs

array([[0.77474391],
       [0.81064502],
       [0.82023146],
       [0.82007216],
       [0.81557674],
       [0.86011543],
       [0.84989855],
       [0.85568934],
       [0.86489495],
       [0.89565634],
       [0.89609264],
       [0.87892827],
       [0.85363907],
       [0.88235019],
       [0.91108904],
       [0.91144924],
       [0.92321769],
       [0.93813088],
       [0.93323366],
       [0.94490504],
       [0.96191704],
       [0.98050142],
       [0.9598321 ],
       [0.98289803],
       [1.        ],
       [0.98913206],
       [0.96945338],
       [0.88741347],
       [0.88786381],
       [0.81230043],
       [0.85688765],
       [0.89702781],
       [0.86603779],
       [0.79420106],
       [0.88259252],
       [0.79456126],
       [0.77161303],
       [0.64462604],
       [0.69250327],
       [0.72450457],
       [0.76905712],
       [0.82062633],
       [0.81650498],
       [0.8454378 ],
       [0.8463728 ],
       [0.89328053],
       [0.90510428],
       [0.912

In [48]:
test_features = []  
for i in range(50, 372):  
    test_features.append(test_inputs[i-50:i, 0])

In [49]:
test_features = np.array(test_features)  
test_features = np.reshape(test_features, (test_features.shape[0], test_features.shape[1], 1))

In [58]:
(test_features[19])

array([[0.94490504],
       [0.96191704],
       [0.98050142],
       [0.9598321 ],
       [0.98289803],
       [1.        ],
       [0.98913206],
       [0.96945338],
       [0.88741347],
       [0.88786381],
       [0.81230043],
       [0.85688765],
       [0.89702781],
       [0.86603779],
       [0.79420106],
       [0.88259252],
       [0.79456126],
       [0.77161303],
       [0.64462604],
       [0.69250327],
       [0.72450457],
       [0.76905712],
       [0.82062633],
       [0.81650498],
       [0.8454378 ],
       [0.8463728 ],
       [0.89328053],
       [0.90510428],
       [0.91273751],
       [0.87074797],
       [0.9257528 ],
       [0.        ],
       [0.01176152],
       [0.01883373],
       [0.02213084],
       [0.0234192 ],
       [0.02051687],
       [0.02231779],
       [0.0451621 ],
       [0.05175625],
       [0.04911722],
       [0.057637  ],
       [0.04661669],
       [0.07125491],
       [0.04798123],
       [0.06667637],
       [0.08896652],
       [0.102

In [54]:
features_set

array([[[0.        ],
        [0.01176152],
        [0.01883373],
        ...,
        [0.20041697],
        [0.23020176],
        [0.24618863]],

       [[0.01176152],
        [0.01883373],
        [0.02213084],
        ...,
        [0.23020176],
        [0.24618863],
        [0.23924113]],

       [[0.01883373],
        [0.02213084],
        [0.0234192 ],
        ...,
        [0.24618863],
        [0.23924113],
        [0.2468605 ]],

       ...,

       [[0.8769404 ],
        [0.76351576],
        [0.79995718],
        ...,
        [0.8463728 ],
        [0.89328053],
        [0.90510428]],

       [[0.76351576],
        [0.79995718],
        [0.77474391],
        ...,
        [0.89328053],
        [0.90510428],
        [0.91273751]],

       [[0.79995718],
        [0.77474391],
        [0.81064502],
        ...,
        [0.90510428],
        [0.91273751],
        [0.87074797]]])

In [53]:
test_features

array([[[0.77474391],
        [0.81064502],
        [0.82023146],
        ...,
        [0.91273751],
        [0.87074797],
        [0.9257528 ]],

       [[0.81064502],
        [0.82023146],
        [0.82007216],
        ...,
        [0.87074797],
        [0.9257528 ],
        [0.        ]],

       [[0.82023146],
        [0.82007216],
        [0.81557674],
        ...,
        [0.9257528 ],
        [0.        ],
        [0.01176152]],

       ...,

       [[0.8769404 ],
        [0.76351576],
        [0.79995718],
        ...,
        [0.8463728 ],
        [0.89328053],
        [0.90510428]],

       [[0.76351576],
        [0.79995718],
        [0.77474391],
        ...,
        [0.89328053],
        [0.90510428],
        [0.91273751]],

       [[0.79995718],
        [0.77474391],
        [0.81064502],
        ...,
        [0.90510428],
        [0.91273751],
        [0.87074797]]])