In [2]:
from sklearn.preprocessing import MinMaxScaler

In [4]:
import pandas as pd

In [5]:
sp500_training_complete = pd.read_csv("GSPC.csv")

In [6]:
sp500_training_processed = sp500_training_complete.iloc[:, 4:5].values  

In [7]:
scaler = MinMaxScaler(feature_range = (0, 1))

sp500_training_scaled = scaler.fit_transform(sp500_training_processed)

In [17]:
np.array(sp500_training_scaled)

array([[0.        ],
       [0.01176152],
       [0.01883373],
       [0.02213084],
       [0.0234192 ],
       [0.02051687],
       [0.02231779],
       [0.0451621 ],
       [0.05175625],
       [0.04911722],
       [0.057637  ],
       [0.04661669],
       [0.07125491],
       [0.04798123],
       [0.06667637],
       [0.08896652],
       [0.10232112],
       [0.12571258],
       [0.11333458],
       [0.10027084],
       [0.1090262 ],
       [0.09749323],
       [0.07373472],
       [0.08332818],
       [0.10106743],
       [0.13452332],
       [0.1427661 ],
       [0.14246137],
       [0.15494329],
       [0.14230207],
       [0.1176499 ],
       [0.1229627 ],
       [0.10181548],
       [0.1171928 ],
       [0.13992617],
       [0.15510952],
       [0.14253062],
       [0.14166478],
       [0.15046165],
       [0.17906893],
       [0.18964601],
       [0.1909413 ],
       [0.19715453],
       [0.21625147],
       [0.22080921],
       [0.22153654],
       [0.22103776],
       [0.200

In [21]:
def method(x,a,b):
    return (((b - a)*(x - min(x))) / (max(x) - min(x))) + a

In [22]:
my = method(sp500_training_processed,0,1)
np.array(my)

array([[0.        ],
       [0.01176152],
       [0.01883373],
       [0.02213084],
       [0.0234192 ],
       [0.02051687],
       [0.02231779],
       [0.0451621 ],
       [0.05175625],
       [0.04911722],
       [0.057637  ],
       [0.04661669],
       [0.07125491],
       [0.04798123],
       [0.06667637],
       [0.08896652],
       [0.10232112],
       [0.12571258],
       [0.11333458],
       [0.10027084],
       [0.1090262 ],
       [0.09749323],
       [0.07373472],
       [0.08332818],
       [0.10106743],
       [0.13452332],
       [0.1427661 ],
       [0.14246137],
       [0.15494329],
       [0.14230207],
       [0.1176499 ],
       [0.1229627 ],
       [0.10181548],
       [0.1171928 ],
       [0.13992617],
       [0.15510952],
       [0.14253062],
       [0.14166478],
       [0.15046165],
       [0.17906893],
       [0.18964601],
       [0.1909413 ],
       [0.19715453],
       [0.21625147],
       [0.22080921],
       [0.22153654],
       [0.22103776],
       [0.200

In [23]:
my == sp500_training_scaled

array([[ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [19]:
np.array_equal(my, sp500_training_scaled)

False

In [14]:
import numpy as np

In [38]:
np.append(np.append(my,sp500_training_scaled, axis=1),my-sp500_training_scaled, axis=1)

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 1.17615151e-02,  1.17615151e-02, -5.37764278e-17],
       [ 1.88337282e-02,  1.88337282e-02, -2.42861287e-17],
       [ 2.21308420e-02,  2.21308420e-02,  2.77555756e-17],
       [ 2.34191969e-02,  2.34191969e-02, -9.36750677e-17],
       [ 2.05168680e-02,  2.05168680e-02,  3.46944695e-18],
       [ 2.23177914e-02,  2.23177914e-02,  2.77555756e-17],
       [ 4.51621031e-02,  4.51621031e-02, -1.17961196e-16],
       [ 5.17562455e-02,  5.17562455e-02, -1.59594560e-16],
       [ 4.91172190e-02,  4.91172190e-02, -4.85722573e-17],
       [ 5.76370026e-02,  5.76370026e-02, -4.85722573e-17],
       [ 4.66166917e-02,  4.66166917e-02, -9.02056208e-17],
       [ 7.12549094e-02,  7.12549094e-02, -9.71445147e-17],
       [ 4.79812306e-02,  4.79812306e-02, -1.52655666e-16],
       [ 6.66763736e-02,  6.66763736e-02, -1.24900090e-16],
       [ 8.89665158e-02,  8.89665158e-02, -2.77555756e-17],
       [ 1.02321119e-01,  1.02321119e-01

In [27]:
my.shape

(322, 1)